# Generated by Django 4.2.7 on 2023-12-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_message_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='updated',
            new_name='update',
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.message'),
        ),
    ]
